--
-- Database: 'dbtest'
--

-- --------------------------------------

--
-- table structure for table users
--


CREATE TABLE  "HORAS_SEMANALES"
   (	"CREDITOS" NUMBER NOT NULL ENABLE,
	"HORAS" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "HORAS_SEMANALES_PK" PRIMARY KEY ("CREDITOS")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PROGRAMA"
   (	"ID_PROGRAMA" NUMBER NOT NULL ENABLE,
	"ID_PRO" NUMBER NOT NULL ENABLE,
	"CREDITOS" NUMBER NOT NULL ENABLE,
	"HORARIO" VARCHAR2(8) NOT NULL ENABLE,
	"CANT_SESIONES" NUMBER NOT NULL ENABLE,
	"F_INICIO" VARCHAR2(8) NOT NULL ENABLE,
	"F_TERMINO" VARCHAR2(8) NOT NULL ENABLE,
	"DESCRIPCION" VARCHAR2(200) NOT NULL ENABLE,
	"P_ASISTENCIA" NUMBER NOT NULL ENABLE,
	"NOTA_FINAL" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "PROGRAMA_PK" PRIMARY KEY ("ID_PROGRAMA", "ID_PRO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "ESTUDIANTES_PROPONENTES"
   (	"ID_EPRO" NUMBER NOT NULL ENABLE,
	"ID_PRO" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "ESTUDIANTES_PROPONENTES_PK" PRIMARY KEY ("ID_EPRO", "ID_PRO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "TALLER_LIBRE"
   (	"ID_EPRO" NUMBER NOT NULL ENABLE,
	"ID_TALLER" NUMBER NOT NULL ENABLE,
	"ID_ENCUESTA" NUMBER NOT NULL ENABLE,
	"ID_PRO" NUMBER NOT NULL ENABLE,
	"ID_ESTUDIANTE" NUMBER NOT NULL ENABLE,
	"INSCRITOS" NUMBER NOT NULL ENABLE,
	"ESTADO" NUMBER NOT NULL ENABLE,
	"MOTIVO" NUMBER NOT NULL ENABLE,
	"PROFESOR" VARCHAR2(45) NOT NULL ENABLE,
	"NAME" VARCHAR2(45) NOT NULL ENABLE,
	 CONSTRAINT "TALLER_LIBRE_PK" PRIMARY KEY ("ID_TALLER")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "ESTUDIANTES"
   (	"ID_ESTUDIANTE" NUMBER NOT NULL ENABLE,
	"NOMBRE" VARCHAR2(45) NOT NULL ENABLE,
	"BANEADO" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "ESTUDIANTES_PK" PRIMARY KEY ("ID_ESTUDIANTE")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "SESION"
   (	"ID_PROGRAMA" NUMBER NOT NULL ENABLE,
	"N_SESION" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "SESION_PK" PRIMARY KEY ("ID_PROGRAMA", "N_SESION")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "INFO_SESION"
   (	"N_SESION" NUMBER NOT NULL ENABLE,
	"NOMBRE_SESION" VARCHAR2(45) NOT NULL ENABLE,
	"ACTIVIDAD" VARCHAR2(200) NOT NULL ENABLE,
	 CONSTRAINT "INFO_SESION_PK" PRIMARY KEY ("N_SESION")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "COMPETENCIAS_ESP"
   (	"ID_PROGRAMA" NUMBER NOT NULL ENABLE,
	"COMPETENCIAS_ESPECIFICAS" VARCHAR2(45) NOT NULL ENABLE,
	 CONSTRAINT "COMPETENCIAS_ESP_PK" PRIMARY KEY ("ID_PROGRAMA", "COMPETENCIAS_ESPECIFICAS")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "ENCUESTA"
   (	"ID_ENCUESTA" NUMBER NOT NULL ENABLE,
	"SEMESTRE" NUMBER NOT NULL ENABLE,
	"ID_PROGRAMA(PK)" NUMBER NOT NULL ENABLE,
	"MAS_RESCATABLE" VARCHAR2(200) NOT NULL ENABLE,
	"MENOS_RESCATABLE" VARCHAR2(200) NOT NULL ENABLE,
	 CONSTRAINT "ENCUESTA_PK" PRIMARY KEY ("ID_ENCUESTA", "SEMESTRE")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "REQ_ENT"
   (	"ID_PROGRAMA" NUMBER NOT NULL ENABLE,
	"REQUISITOS_ENTRADA" VARCHAR2(45) NOT NULL ENABLE,
	 CONSTRAINT "REQ_ENT_PK" PRIMARY KEY ("REQUISITOS_ENTRADA", "ID_PROGRAMA")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "COMPETENCIAS_TRANS"
   (	"ID_PROGRAMA" NUMBER NOT NULL ENABLE,
	"OBJETIVOS" VARCHAR2(45) NOT NULL ENABLE,
	 CONSTRAINT "COMPETENCIAS_TRANS_PK" PRIMARY KEY ("ID_PROGRAMA", "OBJETIVOS")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PAGO"
   (	"ID_PAGO" NUMBER NOT NULL ENABLE,
	"ID_EPRO" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "PAGO_PK" PRIMARY KEY ("ID_PAGO", "ID_EPRO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "OBJETIVOS"
   (	"ID_PROGRAMA" NUMBER NOT NULL ENABLE,
	"OBJETIVO" VARCHAR2(45) NOT NULL ENABLE,
	 CONSTRAINT "OBJETIVOS_PK" PRIMARY KEY ("ID_PROGRAMA", "OBJETIVO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "MONETARIO"
   (	"ID_PAGO" NUMBER NOT NULL ENABLE,
	"ID_MONETARIO" NUMBER NOT NULL ENABLE,
	"MONTO" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "MONETARIO_PK" PRIMARY KEY ("ID_MONETARIO", "ID_PAGO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "CONVALIDACION"
   (	"ID_PAGO" NUMBER NOT NULL ENABLE,
	"ID_CONVALIDACION" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "CONVALIDACION_PK" PRIMARY KEY ("ID_CONVALIDACION", "ID_PAGO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "EXALUMNOS"
   (	"ID_PRO" NUMBER NOT NULL ENABLE,
	"ID_EXALUMNO" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "EXALUMNOS_PK" PRIMARY KEY ("ID_EXALUMNO", "ID_PRO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "ESTUDIANTES_CURSAN"
   (	"ID_ASIGNATURA" NUMBER NOT NULL ENABLE,
	"ID_ESTUDIANTE" NUMBER NOT NULL ENABLE,
	"SEMESTRE" NUMBER NOT NULL ENABLE,
	"ID_TALLER" NUMBER NOT NULL ENABLE,
	"IS_CONVALIDADO" NUMBER NOT NULL ENABLE,
	"ASISTENCIA" NUMBER NOT NULL ENABLE,
	"NOTAS" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "ESTUDIANTES_CURSAN_PK" PRIMARY KEY ("ID_TALLER", "ID_ESTUDIANTE")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "EMPRESAS"
   (	"ID_PRO" NUMBER NOT NULL ENABLE,
	"ID_EMPRESA" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "EMPRESAS_PK" PRIMARY KEY ("ID_EMPRESA", "ID_PRO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "METODOLOGIA"
   (	"ID_PROGRAMA" NUMBER NOT NULL ENABLE,
	"METODOLOGIA" VARCHAR2(45) NOT NULL ENABLE,
	 CONSTRAINT "METODOLOGIA_PK" PRIMARY KEY ("METODOLOGIA", "ID_PROGRAMA")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PROFESORES"
   (	"ID_PRO" NUMBER NOT NULL ENABLE,
	"ID_PROFESOR" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "PROFESORES_PK" PRIMARY KEY ("ID_PROFESOR", "ID_PRO")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "USUARIO"
   (	"ID_USUARIO" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(45) NOT NULL ENABLE,
	"CONTRASEÑA" VARCHAR2(45) NOT NULL ENABLE,
	"PRIVILEGIO" NUMBER NOT NULL ENABLE,
	"ID_ESTUDIANTE" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID_USUARIO", "ID_ESTUDIANTE")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PREREQ"
   (	"ID_PROGRAMA" NUMBER NOT NULL ENABLE,
	"PREREQUISITOS" VARCHAR2(45) NOT NULL ENABLE,
	 CONSTRAINT "PREREQ_PK" PRIMARY KEY ("ID_PROGRAMA", "PREREQUISITOS")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PROPONENTE"
   (	"ID_PRO" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(45) NOT NULL ENABLE,
	 CONSTRAINT "PROPONENTE_PK" PRIMARY KEY ("ID_PRO")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "PROGRAMA" ADD CONSTRAINT "PROGRAMA_FK" FOREIGN KEY ("CREDITOS")
	  REFERENCES  "HORAS_SEMANALES" ("CREDITOS") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "TALLER_LIBRE" ADD CONSTRAINT "TALLER_LIBRE_FK" FOREIGN KEY ("ID_EPRO", "ID_PRO")
	  REFERENCES  "ESTUDIANTES_PROPONENTES" ("ID_EPRO", "ID_PRO") ON DELETE CASCADE ENABLE
/
